// Self-hosts Google Fonts: downloads the exact woff2 files Google serves for the
// weights we use (latin + latin-ext) and emits local @font-face rules into
// src/fonts.css, so the site has no render-blocking third-party font request and
// no calls to Google. Run with `npm run fonts:self-host` to refresh.
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outFonts = resolve(root, 'public/fonts')
mkdirSync(outFonts, { recursive: true })

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600&display=swap'
// A modern desktop UA makes Google return woff2 (its smallest modern format).
const UA =
  'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36'
// All site content is latin (incl. German ä/ö/ü/ß, which live in the latin
// subset), so latin-ext etc. are never fetched — keep only latin to stay lean.
const KEEP_SUBSETS = new Set(['latin'])
const slug = (family) => family.toLowerCase().replace(/\s+/g, '-')

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

const blockRe = /\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g
const pick = (body, key) => (body.match(new RegExp(`${key}:\\s*([^;]+);`)) || [])[1]?.trim()

const faces = []
let m
let kept = 0
let skipped = 0
while ((m = blockRe.exec(css))) {
  const subset = m[1]
  const body = m[2]
  if (!KEEP_SUBSETS.has(subset)) {
    skipped++
    continue
  }
  const family = (pick(body, 'font-family') || '').replace(/['"]/g, '')
  const weight = pick(body, 'font-weight')
  const style = pick(body, 'font-style') || 'normal'
  const unicode = pick(body, 'unicode-range')
  const url = (body.match(/src:\s*url\(([^)]+)\)/) || [])[1]?.replace(/['"]/g, '')
  if (!family || !weight || !url) continue

  const file = `${slug(family)}-${weight}-${subset}.woff2`
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  writeFileSync(resolve(outFonts, file), buf)
  kept++

  faces.push(
    `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;` +
      `src:url('/fonts/${file}') format('woff2');unicode-range:${unicode}}`,
  )
  console.log(`${file}  (${(buf.length / 1024).toFixed(1)}KB)`)
}

if (!kept) throw new Error('No font-faces parsed — Google CSS format may have changed.')

const out =
  '/* Auto-generated by scripts/build-fonts.mjs — self-hosted Inter + JetBrains Mono.\n' +
  '   Run `npm run fonts:self-host` to regenerate. Do not edit by hand. */\n' +
  faces.join('\n') +
  '\n'
writeFileSync(resolve(root, 'src/fonts.css'), out)
console.log(`\nWrote src/fonts.css with ${kept} @font-face rules (skipped ${skipped} non-latin subsets).`)
